CREATE DATABASE IF NOT EXISTS monitoria_app CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE monitoria_app;

CREATE TABLE IF NOT EXISTS usuarios (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(120) NOT NULL,
  email VARCHAR(120) NOT NULL UNIQUE,
  senha_hash VARCHAR(255) NOT NULL,
  papel ENUM('ALUNO', 'MONITOR', 'PROFESSOR', 'ADMIN') NOT NULL,
  status ENUM('PENDENTE', 'ATIVO', 'INATIVO') NOT NULL DEFAULT 'PENDENTE',
  senha_temporaria BOOLEAN NOT NULL DEFAULT TRUE,
  contato VARCHAR(120) NULL,
  disponibilidade TEXT NULL,
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS password_reset_tokens (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  usuario_id BIGINT UNSIGNED NOT NULL,
  token VARCHAR(64) NOT NULL UNIQUE,
  expira_em DATETIME NOT NULL,
  usado BOOLEAN NOT NULL DEFAULT FALSE,
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_password_reset_usuario
    FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS disciplinas (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  codigo VARCHAR(32) NOT NULL UNIQUE,
  nome VARCHAR(120) NOT NULL,
  professor_id BIGINT UNSIGNED NOT NULL,
  status ENUM('ATIVA', 'INATIVA') NOT NULL DEFAULT 'ATIVA',
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_disciplina_professor
    FOREIGN KEY (professor_id) REFERENCES usuarios (id)
);

CREATE TABLE IF NOT EXISTS disciplina_alunos (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  disciplina_id BIGINT UNSIGNED NOT NULL,
  aluno_id BIGINT UNSIGNED NOT NULL,
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_disciplina_aluno_disciplina
    FOREIGN KEY (disciplina_id) REFERENCES disciplinas (id)
    ON DELETE CASCADE,
  CONSTRAINT fk_disciplina_aluno_usuario
    FOREIGN KEY (aluno_id) REFERENCES usuarios (id)
    ON DELETE CASCADE,
  CONSTRAINT uq_disciplina_aluno
    UNIQUE (disciplina_id, aluno_id)
);

CREATE TABLE IF NOT EXISTS monitorias (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  disciplina_id BIGINT UNSIGNED NOT NULL,
  professor_id BIGINT UNSIGNED NOT NULL,
  aluno_id BIGINT UNSIGNED NOT NULL,
  status ENUM('PENDENTE_APROVACAO', 'ATIVO', 'REJEITADO') NOT NULL DEFAULT 'PENDENTE_APROVACAO',
  motivo_rejeicao VARCHAR(255) NULL,
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_monitoria_disciplina
    FOREIGN KEY (disciplina_id) REFERENCES disciplinas (id),
  CONSTRAINT fk_monitoria_professor
    FOREIGN KEY (professor_id) REFERENCES usuarios (id),
  CONSTRAINT fk_monitoria_aluno
    FOREIGN KEY (aluno_id) REFERENCES usuarios (id),
  CONSTRAINT uq_monitoria_unica
    UNIQUE (disciplina_id, aluno_id)
);
