CREATE DATABASE IF NOT EXISTS monitoria_app CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE monitoria_app;

CREATE TABLE IF NOT EXISTS usuarios (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(120) NOT NULL,
  email VARCHAR(120) NOT NULL UNIQUE,
  senha_hash VARCHAR(255) NOT NULL,
  papel ENUM('ALUNO', 'MONITOR', 'PROFESSOR', 'ADMIN') NOT NULL,
  status ENUM('PENDENTE', 'ATIVO', 'INATIVO') NOT NULL DEFAULT 'PENDENTE',
  senha_temporaria BOOLEAN NOT NULL DEFAULT TRUE,
  contato VARCHAR(120) NULL,
  disponibilidade TEXT NULL,
  carga_horaria_semanal TINYINT NOT NULL DEFAULT 1,
  modo_2h ENUM('CONSECUTIVAS', 'SEPARADAS') NOT NULL DEFAULT 'CONSECUTIVAS',
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS password_reset_tokens (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  usuario_id BIGINT UNSIGNED NOT NULL,
  token VARCHAR(64) NOT NULL UNIQUE,
  expira_em DATETIME NOT NULL,
  usado BOOLEAN NOT NULL DEFAULT FALSE,
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_password_reset_usuario
    FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS disciplinas (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  codigo VARCHAR(32) NOT NULL UNIQUE,
  nome VARCHAR(120) NOT NULL,
  professor_id BIGINT UNSIGNED NOT NULL,
  status ENUM('ATIVA', 'INATIVA') NOT NULL DEFAULT 'ATIVA',
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_disciplina_professor
    FOREIGN KEY (professor_id) REFERENCES usuarios (id)
);

CREATE TABLE IF NOT EXISTS disciplina_alunos (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  disciplina_id BIGINT UNSIGNED NOT NULL,
  aluno_id BIGINT UNSIGNED NOT NULL,
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_disciplina_aluno_disciplina
    FOREIGN KEY (disciplina_id) REFERENCES disciplinas (id)
    ON DELETE CASCADE,
  CONSTRAINT fk_disciplina_aluno_usuario
    FOREIGN KEY (aluno_id) REFERENCES usuarios (id)
    ON DELETE CASCADE,
  CONSTRAINT uq_disciplina_aluno
    UNIQUE (disciplina_id, aluno_id)
);

CREATE TABLE IF NOT EXISTS monitorias (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  disciplina_id BIGINT UNSIGNED NOT NULL,
  professor_id BIGINT UNSIGNED NOT NULL,
  aluno_id BIGINT UNSIGNED NOT NULL,
  status ENUM('PENDENTE_APROVACAO', 'ATIVO', 'REJEITADO') NOT NULL DEFAULT 'PENDENTE_APROVACAO',
  motivo_rejeicao VARCHAR(255) NULL,
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_monitoria_disciplina
    FOREIGN KEY (disciplina_id) REFERENCES disciplinas (id),
  CONSTRAINT fk_monitoria_professor
    FOREIGN KEY (professor_id) REFERENCES usuarios (id),
  CONSTRAINT fk_monitoria_aluno
    FOREIGN KEY (aluno_id) REFERENCES usuarios (id),
  CONSTRAINT uq_monitoria_unica
    UNIQUE (disciplina_id, aluno_id)
);

CREATE TABLE IF NOT EXISTS disponibilidades (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  disciplina_id BIGINT UNSIGNED NOT NULL,
  monitor_id BIGINT UNSIGNED NOT NULL,
  data_inicio DATETIME NOT NULL,
  data_fim DATETIME NOT NULL,
  local VARCHAR(255) NULL,
  status ENUM('DISPONIVEL', 'AGENDADO', 'BLOQUEADO') NOT NULL DEFAULT 'DISPONIVEL',
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_disponibilidade_disciplina
    FOREIGN KEY (disciplina_id) REFERENCES disciplinas (id),
  CONSTRAINT fk_disponibilidade_monitor
    FOREIGN KEY (monitor_id) REFERENCES usuarios (id)
);

CREATE TABLE IF NOT EXISTS agendamentos (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  disponibilidade_id BIGINT UNSIGNED NOT NULL,
  aluno_id BIGINT UNSIGNED NOT NULL,
  status ENUM('CONFIRMADO', 'CANCELADO') NOT NULL DEFAULT 'CONFIRMADO',
  motivo_cancelamento VARCHAR(255) NULL,
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_agendamento_disponibilidade
    FOREIGN KEY (disponibilidade_id) REFERENCES disponibilidades (id) ON DELETE CASCADE,
  CONSTRAINT fk_agendamento_aluno
    FOREIGN KEY (aluno_id) REFERENCES usuarios (id)
);

CREATE TABLE IF NOT EXISTS monitor_disponibilidade (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  monitor_id BIGINT UNSIGNED NOT NULL,
  weekday TINYINT NOT NULL,
  hora_inicio TIME NOT NULL,
  status ENUM('LIVRE', 'INDISPONIVEL') NOT NULL DEFAULT 'LIVRE',
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_monitor_disponibilidade_monitor
    FOREIGN KEY (monitor_id) REFERENCES usuarios (id) ON DELETE CASCADE,
  CONSTRAINT uq_monitor_disponibilidade
    UNIQUE (monitor_id, weekday, hora_inicio)
);

CREATE TABLE IF NOT EXISTS votacoes (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  disciplina_id BIGINT UNSIGNED NOT NULL,
  semana_inicio DATE NOT NULL,
  semana_fim DATE NOT NULL,
  status ENUM('ABERTA', 'FECHADA') NOT NULL DEFAULT 'ABERTA',
  carga_horaria_semanal TINYINT NOT NULL DEFAULT 1,
  modo_2h ENUM('CONSECUTIVAS', 'SEPARADAS') NOT NULL DEFAULT 'CONSECUTIVAS',
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_votacao_disciplina
    FOREIGN KEY (disciplina_id) REFERENCES disciplinas (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS votacao_opcoes (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  votacao_id BIGINT UNSIGNED NOT NULL,
  modo ENUM('BLOCO_2H', 'DOIS_1H', 'SLOT_1H') NOT NULL,
  slot1_weekday TINYINT NOT NULL,
  slot1_hora_inicio TIME NOT NULL,
  slot2_weekday TINYINT NULL,
  slot2_hora_inicio TIME NULL,
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_votacao_opcao
    FOREIGN KEY (votacao_id) REFERENCES votacoes (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS votos (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  votacao_id BIGINT UNSIGNED NOT NULL,
  opcao_id BIGINT UNSIGNED NOT NULL,
  aluno_id BIGINT UNSIGNED NOT NULL,
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_voto_votacao
    FOREIGN KEY (votacao_id) REFERENCES votacoes (id) ON DELETE CASCADE,
  CONSTRAINT fk_voto_opcao
    FOREIGN KEY (opcao_id) REFERENCES votacao_opcoes (id) ON DELETE CASCADE,
  CONSTRAINT fk_voto_aluno
    FOREIGN KEY (aluno_id) REFERENCES usuarios (id),
  CONSTRAINT uq_voto_unico
    UNIQUE (votacao_id, aluno_id, opcao_id)
);

CREATE TABLE IF NOT EXISTS monitoria_sessoes (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  disciplina_id BIGINT UNSIGNED NOT NULL,
  monitor_id BIGINT UNSIGNED NOT NULL,
  data_inicio DATETIME NOT NULL,
  data_fim DATETIME NOT NULL,
  status ENUM('AGENDADA', 'CANCELADA', 'CONCLUIDA') NOT NULL DEFAULT 'AGENDADA',
  motivo_cancelamento VARCHAR(255) NULL,
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_monitoria_sessao_disciplina
    FOREIGN KEY (disciplina_id) REFERENCES disciplinas (id) ON DELETE CASCADE,
  CONSTRAINT fk_monitoria_sessao_monitor
    FOREIGN KEY (monitor_id) REFERENCES usuarios (id)
);

CREATE TABLE IF NOT EXISTS presencas (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  sessao_id BIGINT UNSIGNED NOT NULL,
  aluno_id BIGINT UNSIGNED NOT NULL,
  status ENUM('CONFIRMADA', 'AUSENTE', 'CANCELADA') NOT NULL,
  atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_presenca_sessao
    FOREIGN KEY (sessao_id) REFERENCES monitoria_sessoes (id) ON DELETE CASCADE,
  CONSTRAINT fk_presenca_aluno
    FOREIGN KEY (aluno_id) REFERENCES usuarios (id),
  CONSTRAINT uq_presenca_unica
    UNIQUE (sessao_id, aluno_id)
);
