ALTER TABLE usuarios
  ADD COLUMN carga_horaria_semanal TINYINT NOT NULL DEFAULT 1 AFTER disponibilidade,
  ADD COLUMN modo_2h ENUM('CONSECUTIVAS', 'SEPARADAS') NOT NULL DEFAULT 'CONSECUTIVAS' AFTER carga_horaria_semanal;
