ALTER TABLE votacoes
  ADD COLUMN IF NOT EXISTS carga_horaria_semanal TINYINT NOT NULL DEFAULT 1 AFTER status,
  ADD COLUMN IF NOT EXISTS modo_2h ENUM('CONSECUTIVAS', 'SEPARADAS') NOT NULL DEFAULT 'CONSECUTIVAS' AFTER carga_horaria_semanal;

ALTER TABLE votacao_opcoes
  MODIFY COLUMN modo ENUM('BLOCO_2H', 'DOIS_1H', 'SLOT_1H') NOT NULL;
