ALTER TABLE usuarios
  ADD COLUMN IF NOT EXISTS carga_horaria_semanal TINYINT NOT NULL DEFAULT 1 AFTER disponibilidade,
  ADD COLUMN IF NOT EXISTS modo_2h ENUM('CONSECUTIVAS', 'SEPARADAS') NOT NULL DEFAULT 'CONSECUTIVAS' AFTER carga_horaria_semanal;
